name: "Docs"

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**' # On updating docs

jobs:
  build:
    name: Deploy EmpowerChain docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.22

      - run: earthly --ci --output +build
        working-directory: ./docs
      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'fr-par' 
          AWS_S3_ENDPOINT: 'https://s3.fr-par.scw.cloud'
          SOURCE_DIR: './docs/public'