name: Create release

on:
  push:
    tags:
      - "v*" # Push events to matching v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.22

      - run: earthly --ci --output +build-all --VERSION_NUMBER=${{ github.ref_name }}
        working-directory: ./chain

      - run: |
          zip -q empowerd-${{ github.ref_name }}-linux-amd64.zip empowerd-${{ github.ref_name }}-linux-amd64 && rm empowerd-${{ github.ref_name }}-linux-amd64 \
          zip -q empowerd-${{ github.ref_name }}-linux-arm64.zip empowerd-${{ github.ref_name }}-linux-arm64 && rm empowerd-${{ github.ref_name }}-linux-arm64 \
          zip -q empowerd-${{ github.ref_name }}-darwin-amd64.zip empowerd-${{ github.ref_name }}-darwin-amd64 && rm empowerd-${{ github.ref_name }}-darwin-amd64 \
          zip -q empowerd-${{ github.ref_name }}-darwin-arm64.zip empowerd-${{ github.ref_name }}-darwin-arm64 && rm empowerd-${{ github.ref_name }}-darwin-arm64 \
          zip -q empowerd-${{ github.ref_name }}-windows-amd64.zip empowerd-${{ github.ref_name }}-windows-amd64 && rm empowerd-${{ github.ref_name }}-windows-amd64
              
        working-directory: ./chain/build
      # TODO: 1. Generate release notes
      # TODO: 2. Build darwin + darwin arm version (maybe windows too)

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: ./chain/build/*