name: "Test"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'chain/**'

jobs:
  test:
    name: Test EmpowerChain
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.22

      - run: earthly --ci +test-with-coverage
        working-directory: ./chain

      - uses: codecov/codecov-action@v3
        with:
          files: ./chain/coverage.out
          flags: chain

      - run: earthly --ci +smoketest
        working-directory: ./chain
